### ISSUE TITLE
Issue with `RegularIdentifier` and reserved keywords

### ISSUE THREAD

**Issue by viladimiru** [gravity-ui/websql-autocomplete#106]
Need to try to create group with all reserved keywords and add them in `RegularIdentifier`
![telegram-cloud-photo-size-2-5436347824506786535-y](https://github.com/gravity-ui/websql-autocomplete/assets/26850586/58efcc3a-0fc3-4385-845e-410cc75cd4ff)

**Comment by NikitaShkaruba** [comment]
This issue is irrelevant because we've migrated to ANTLR
